In [20]:
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import unpack, pack
from ark.client.comm_infrastructure.instance_node import InstanceNode

SIM = True

class GO2ControllerNode(InstanceNode):

    def __init__(self):
        '''
        Initialize the GO2.
        This class is responsible for controlling the Husky robot's joints.
        '''
        super().__init__("GO2Controller")

        if SIM == True:
            self.joint_group_command = self.create_publisher("UnitreeGo2/joint_group_command/sim", joint_group_command_t)

            self.state = self.create_listener("UnitreeGo2/joint_states/sim", joint_state_t)

controller = GO2ControllerNode()

[WARNING] [11:34:22.507164] - No global configuration provided. Using default system configuration.
[INFO] [11:34:22.509890] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/GO2Controller_3a0a2996-afb1-41de-b903-f3b0d01bc8dc' with registry.
[INFO] [11:34:22.511017] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/GO2Controller_3a0a2996-afb1-41de-b903-f3b0d01bc8dc' with registry.
[INFO] [11:34:22.512156] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/GO2Controller_3a0a2996-afb1-41de-b903-f3b0d01bc8dc' with registry.
[ERROR] [11:34:22.512477] - Couldn't load config for other 'GO2Controller'
[OK] [11:34:22.513097] - setup publisher UnitreeGo2/joint_group_command/sim[joint_group_command_t]
[OK] [11:34:22.513676] - subscribed to UnitreeGo2/joint_states/sim[joint_state_t]


None


* FL\_hip\_joint
* FL\_thigh\_joint
* FL\_calf\_joint
* FR\_hip\_joint
* FR\_thigh\_joint
* FR\_calf\_joint
* RL\_hip\_joint
* RL\_thigh\_joint
* RL\_calf\_joint
* RR\_hip\_joint
* RR\_thigh\_joint
* RR\_calf\_joint

In [24]:

# FORWARDS
joint_command = [1, 0, 0, 0, 0, 0]
# Velocity Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "all"))

In [17]:
unpack.joint_state(controller.state.get())

({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['FL_hip_joint',
  'FL_thigh_joint',
  'FL_calf_joint',
  'FR_hip_joint',
  'FR_thigh_joint',
  'FR_calf_joint',
  'RL_hip_joint',
  'RL_thigh_joint',
  'RL_calf_joint',
  'RR_hip_joint',
  'RR_thigh_joint',
  'RR_calf_joint'],
 array([ 9.98395096e-01,  5.73586253e-05, -8.37671272e-01,  6.46626586e-04,
         4.77678354e-05, -8.37905534e-01, -5.37067286e-02, -4.86142702e-01,
         3.44827894e-01,  2.18173469e-02,  1.09331965e-02,  4.49893060e-02]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))