In [1]:
import numpy as np
from arktypes import joint_group_command_t, task_space_command_t, joint_state_t
from arktypes.utils import unpack, pack
from ark.client.comm_infrastructure.instance_node import InstanceNode

SIM = True

class GO2ControllerNode(InstanceNode):

    def __init__(self):
        '''
        Initialize the GO2.
        This class is responsible for controlling the Husky robot's joints.
        '''
        super().__init__("GO2Controller")

        if SIM == True:
            self.joint_group_command = self.create_publisher("UnitreeGo2/joint_group_command/sim", joint_group_command_t)

            self.state = self.create_listener("UnitreeGo2/joint_states/sim", joint_state_t)

controller = GO2ControllerNode()

[WARNING] [10:35:15.175109] - No global configuration provided. Using default system configuration.
[INFO] [10:35:15.178039] - Service: Successfully registered '__DEFAULT_SERVICE/GetInfo/GO2Controller_285f9d60-c75f-4729-abee-ca6d4ea5749f' with registry.
[INFO] [10:35:15.180546] - Service: Successfully registered '__DEFAULT_SERVICE/SuspendNode/GO2Controller_285f9d60-c75f-4729-abee-ca6d4ea5749f' with registry.
[INFO] [10:35:15.182388] - Service: Successfully registered '__DEFAULT_SERVICE/RestartNode/GO2Controller_285f9d60-c75f-4729-abee-ca6d4ea5749f' with registry.
[ERROR] [10:35:15.183983] - Couldn't load config for other 'GO2Controller'
[OK] [10:35:15.185083] - setup publisher UnitreeGo2/joint_group_command/sim[joint_group_command_t]
[OK] [10:35:15.186082] - subscribed to UnitreeGo2/joint_states/sim[joint_state_t]


None


* FL\_hip\_joint
* FL\_thigh\_joint
* FL\_calf\_joint
* FR\_hip\_joint
* FR\_thigh\_joint
* FR\_calf\_joint
* RL\_hip\_joint
* RL\_thigh\_joint
* RL\_calf\_joint
* RR\_hip\_joint
* RR\_thigh\_joint
* RR\_calf\_joint

In [5]:

# FORWARDS
joint_command = [0, 0, 0, 0, 0, 0]
# Velocity Control
controller.joint_group_command.publish(pack.joint_group_command(joint_command, "all"))

In [3]:
unpack.joint_state(controller.state.get())

({'seq': 0, 'stamp': {'sec': 0, 'nsec': 0}, 'frame_id': ''},
 ['FL_hip_joint',
  'FL_thigh_joint',
  'FL_calf_joint',
  'FR_hip_joint',
  'FR_thigh_joint',
  'FR_calf_joint',
  'RL_hip_joint',
  'RL_thigh_joint',
  'RL_calf_joint',
  'RR_hip_joint',
  'RR_thigh_joint',
  'RR_calf_joint'],
 array([ 1.00245842e+00, -1.42866959e-04, -9.99934363e-01, -2.32671940e-04,
         1.00172153e+00, -8.36287230e-01,  3.92455558e-02, -1.05533162e-02,
         3.19424695e-03,  3.64306573e-02, -9.26347189e-03,  5.02228746e-03]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))